version: '3.8'

services:
  web:
    build: .
    command: uvicorn careconnect.asgi:application --host 0.0.0.0 --port 9000
    volumes:
      - .:/app
      - media_data:/app/media
      - static_data:/app/staticfiles
    ports:
      - "9000:9000"
    env_file:
      - .env
    depends_on:
      - db
    environment:
      - MONGO_URI=mongodb://db:27018/careconnect
    networks:
      - test

  db:
    image: mongo:4.4
    volumes:
      - mongo_data:/data/db
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_DATABASE: careconnect
    networks:
      - test
    

volumes:
  mongo_data:
  media_data:
  static_data:

networks:
  test:
