version: '3.8'

services:
  web:
    build: .
    command: uvicorn careconnect.asgi:application --host 0.0.0.0 --port 8000

    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - test

  db:
    image: mongo:4.4
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: careconnect

volumes:
  mongo_data:

networks:
  test:
